### ISSUE TITLE
README.md is missing on pypi

### ISSUE THREAD

**Issue by phsteve** [pnpnpn/timeout-decorator#13]
```
$ pip install timeout-decorator
Collecting timeout-decorator
  Downloading timeout-decorator-0.2.0.tar.gz
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-aHm5Rz/timeout-decorator/setup.py", line 24, in <module>
        long_description = open('README.md').read(),
    IOError: [Errno 2] No such file or directory: 'README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

      File "<string>", line 20, in <module>

      File "/tmp/pip-build-aHm5Rz/timeout-decorator/setup.py", line 24, in <module>

        long_description = open('README.md').read(),

    IOError: [Errno 2] No such file or directory: 'README.md'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aHm5Rz/timeout-decorator
```

**Comment by pnpnpn** [comment]
Thanks for letting me know. It should be fixed now -- I forgot to bump the version.

**Comment by phsteve** [comment]
Yep, works great now. Thanks!
