### ISSUE TITLE
ValueError: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by vadimszzz** [pnpnpn/timeout-decorator#75]
```
Traceback (most recent call last):
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 83, in on_output
    _pipe(stdout, stderr)(fd, data)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 43, in pipe
    _output(data)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 122, in exit_handler
    if not frida_utils.process_is_running(frida_device, pid) and str(stderr[:-1]).isdigit():
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/utils.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 75, in new_function
    old = signal.signal(signal.SIGALRM, handler)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
Traceback (most recent call last):
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 83, in on_output
    _pipe(stdout, stderr)(fd, data)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 43, in pipe
    _output(data)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 122, in exit_handler
    if not frida_utils.process_is_running(frida_device, pid) and str(stderr[:-1]).isdigit():
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/utils.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 75, in new_function
    old = signal.signal(signal.SIGALRM, handler)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
ValueError: signal only works in main thread of the main interpreter
```

**Comment by chucklesoclock** [comment]
https://github.com/pnpnpn/timeout-decorator#multithreading
