### ISSUE TITLE
_pickle.PicklingError: Can't pickle <function process_is_running at 0x108fa8b80>: it's not the same object as exynex.frida_utils.process_is_running

### ISSUE THREAD

**Issue by vadimszzz** [pnpnpn/timeout-decorator#76]
```
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/__main__.py", line 83, in <module>
    cli()
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/__main__.py", line 53, in cli
    cli_commands()
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/cli/package.py", line 64, in dump
    package_util.dump_fouldecrypt(**kwargs)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/package.py", line 16, in dump_fouldecrypt
    tmp_dir = shell.exec(frida_device, "mktemp -d", verbose=verbose).stdout.decode("utf-8").strip("\n")
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 158, in exec
    exit_code = _exec_with_exit_code(frida_device, cmd, [_stdout, stdout], [_stderr, stderr])
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 130, in _exec_with_exit_code
    while frida_utils.process_is_running(frida_device, pid):
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/utils.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 92, in new_function
    return timeout_wrapper(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/timeout_decorator/timeout_decorator.py", line 147, in __call__
    self.__process.start()
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function process_is_running at 0x108fa8b80>: it's not the same object as exynex.frida_utils.process_is_running
```

**Comment by tanasecucliciu** [comment]
Did you find a solution for this?
